#!/bin/bash

set -e

if [ ! command -v docker &> /dev/null ]; then
    echo "❌ Docker is not installed."
    echo "Please install Docker before running this script."
    exit 1
fi

if [ ! command -v git &> /dev/null ]; then
    echo "❌ Git is not installed."
    echo "Please install Git before running this script."
    exit 1
fi

mkdir -p ./workdir
cd ./workdir

# git clone the gaia core
git clone https://github.com/gaiaBuildSystem/gaia.git

# call it
./gaia/scripts/init
